name: Update tracker

on:
  schedule:
    - cron: "0 * * * *" # Every 30 minutes
  workflow_dispatch:

jobs:
  poll-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout tracker branch
        uses: actions/checkout@v4
        with:
          ref: tracker
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install requests PyGithub

      - name: Poll pull requests and update files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python process_prs.py
